name: second-workflow
on: workflow_dispatch
jobs:
    second-job:
        runs-on: ubuntu-latest
        steps:
        - name: get chef-repo clone
          run: echo "cloning chef repo from github"
        - name: upload data to chef server
          run:  |
            echo "upload chef-repo data to chef server"
            echo "run knife commands to upload data"
            echo "validate uploaded data"